# Generated by Django 3.0.2 on 2020-04-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEndServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='upsAccount',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PURCHASING'), (2, 'PURCHASED'), (3, 'PACKING'), (4, 'PACKED'), (5, 'LOADING'), (6, 'LOADED'), (7, 'DELIVERING'), (8, 'DELIVERED'), (9, 'CANCEL')], default=0),
        ),
    ]
