# Generated by Django 3.0.5 on 2020-04-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.IntegerField(blank=True, default=None, null=True)),
                ('addr_x', models.IntegerField(default=1)),
                ('addr_y', models.IntegerField(default=1)),
                ('item_str', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PURCHASING'), (2, 'PURCHASED'), (3, 'PACKING'), (4, 'PACKED'), (5, 'LOADING'), (6, 'LOADED'), (7, 'DELIVERING'), (8, 'DELIVERED')], default=0)),
                ('wh', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wh', to='frontEndServer.Warehouse')),
            ],
        ),
    ]
